export interface Album {
    mediaID: number,
    albumName: string,
    releaseDate: string,
    description: string,
    runtime: string,
    numberOfTracks: number,
    coverImg: string,
    genre: string[],
    review: string,
    artist: string,
    spotifyLink: string,
    trackList: string[]
}

export interface AlbumAddition {
  mediaID: number,
  albumName: string,
  releaseDate: string,
  description: string,
  runtime: string,
  numberOfTracks: number,
  coverImg: string,
  genre: string,
  review: string,
  artist: string,
  spotifyLink: string,
  trackList: string
}

/** 
export const ManyAlbums: Album[] = [
  {
    "mediaID": 1,
    "albumName": "The Poison",
    "releaseDate": "2005-10-03",
    "description": "Debut studio album by Welsh heavy metal band Bullet for my Valentine.",
    "runtime": "46:41",
    "numberOfTracks": 13,
    "coverImg": "https://i.scdn.co/image/ab67616d0000b2736aec43f8c78d4e0a1ad8a8b5",
    "genre": ["Metalcore", "Hard Rock"],
    "review":  "The Poison by Bullet For My Valentine is the band`s first album and is one of the classics of old school Metalcore.",
"artist": "Bullet for my Valentine",
    "trackList": [
      "Intro",
      "Her Voice Resides",
      " 4 Words (To Choke Upon)",
      " Tears Dont Fall",
      " Suffocating Under Words of Sorrow (What Can I Do)",
      " Hit the Floor",
      " All These Things I Hate (Revolve Around Me)",
      " Room 409",
      " The Poison",
      " 10 Years Today",
      " Cries in Vain",
      " Spit You Out",
      " The End"
    ],
    "spotifyLink": "<iframe style=\"border-radius:12px\" src=\"https://open.spotify.com/embed/album/58TQcPpRD9XcXhUDWF5P27?utm_source=generator\" width=\"100%\" height=\"352\" frameBorder=\"0\" allowfullscreen=\"\" allow=\"autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture\" loading=\"lazy\"></iframe>"
  },
      {
        "mediaID": 2,
        "albumName": "Scream Aim Fire",
        "releaseDate": "2008-01-28",
        "description": "Second studio album by Welsh heavy metal band Bullet for my Valentine.",
        "runtime": "42:36",
        "numberOfTracks": 11,
        "coverImg": "https://m.media-amazon.com/images/I/81QKcS+vqcL._UF1000,1000_QL80_.jpg",
        "genre": ["Metalcore", "Thrash Metal"],
        "review": "An explosive sophomore effort showcasing Bullet for my Valentine\'s signature blend of aggressive riffs, infectious melodies, and anthemic choruses, making it a standout in the metalcore genre.",
        "artist": "Bullet for my Valentine",
        "trackList": [
          "Scream Aim Fire",
          " Eye of the Storm",
          " Hearts Burst into Fire",
          " Waking the Demon",
          " Disappear",
          " Deliver Us from Evil",
          " Take It Out on Me",
          " Say Goodnight",
          " End of Days",
          " Last to Know",
          " Forever and Always"
        ],
        "spotifyLink": "<iframe style=\"border-radius:12px\" src=\"https://open.spotify.com/embed/album/2mGohCvbL3klQgXyTj7uNB?utm_source=generator\" width=\"100%\" height=\"352\" frameBorder=\"0\" allowfullscreen=\"\" allow=\"autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture\" loading=\"lazy\"></iframe>"
      },
      {
        "mediaID": 3,
        "albumName": "End of Heartache",
        "releaseDate": "2004-05-11",
        "description": "Third studio album by American metalcore band Killswitch Engage evolving their sound to places that remain untouchable even today.",
        "runtime": "39:53",
        "numberOfTracks": 12,
        "coverImg": "https://m.media-amazon.com/images/I/81SU0bsVQmL._UF1000,1000_QL80_.jpg",
        "genre": ["Metalcore"],
        "review": "A landmark album that solidified Killswitch Engage`s status as metalcore pioneers, featuring a perfect balance of raw aggression and poignant lyricism, highlighted by Jesse Leach`s emotionally charged vocals.",
        "artist": "Killswitch Engage",
        "trackList": [
          "A Bid Farewell",
          " Take This Oath",
          " When Darkness Falls",
          " Rose of Sharyn",
          " Inhale",
          " Breathe Life",
          " The End of Heartache",
          " Declaration",
          " World Ablaze",
          " And Embers Rise",
          " Wasted Sacrifice",
          " Hope Is..."
        ],
        "spotifyLink": "<iframe style=\"border-radius:12px\" src=\"https://open.spotify.com/embed/album/5OT73TnmHx6FmTnpwapBsA?utm_source=generator\" width=\"100%\" height=\"352\" frameBorder=\"0\" allowfullscreen=\"\" allow=\"autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture\" loading=\"lazy\"></iframe>"
      },
      {
        "mediaID": 4,
        "albumName": "As Daylight Dies",
        "releaseDate": "2006-11-21",
        "description": "Fourth studio album by American metalcore band Killswitch Engage.",
        "runtime": "42:03",
        "numberOfTracks": 13,
        "coverImg": "https://lastfm.freetls.fastly.net/i/u/ar0/dcf074fa4838914841e5b70357aa16a7.jpg",
        "genre": ["Metalcore"],
        "review": "A powerful follow-up to \"End of Heartache,\" this album further cements Killswitch Engage`s place in metalcore history with its dynamic songwriting, memorable hooks, and intense performances.",
        "artist": "Killswitch Engage",
        "trackList": [
          "Daylight Dies",
          " This Is Absolution",
          " The Arms of Sorrow",
          " Unbroken",
          " My Curse",
          " For You",
          " Still Beats Your Name",
          " Eye of the Storm",
          " Break the Silence",
          " Desperate Times",
          " Reject Yourself",
          " Be One"
        ],
        "spotifyLink": "<iframe style=\"border-radius:12px\" src=\"https://open.spotify.com/embed/album/6iJEtgHTEbVlSS5isIS71z?utm_source=generator\" width=\"100%\" height=\"352\" frameBorder=\"0\" allowfullscreen=\"\" allow=\"autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture\" loading=\"lazy\"></iframe>"
      },
      {
        "mediaID": 5,
        "albumName": "Periphery 1",
        "releaseDate": "2010-04-20",
        "description": "Debut studio album by American progressive metal band Periphery.",
        "runtime": "70:01",
        "numberOfTracks": 14,
        "coverImg": "https://upload.wikimedia.org/wikipedia/en/f/fd/Periphery.jpg",
        "genre": ["Progressive Metal", "Djent"],
        "review": "A groundbreaking debut album that redefines the boundaries of progressive metal with its intricate rhythms, complex song structures, and virtuosic musicianship, establishing Periphery as leaders of the djent movement.",
        "artist": "Periphery",
        "trackList": [
          "Insomnia",
          " The Walk",
          " Letter Experiment",
          " Jetpacks Was Yes!",
          " Light",
          " All New Materials",
          " Buttersnips",
          " Icarus Lives!",
          " Totla Mad",
          " Ow My Feelings",
          " Zyglrox",
          " Racecar"
        ],
        "spotifyLink": "<iframe style=\"border-radius:12px\" src=\"https://open.spotify.com/embed/album/2N0UCSLHhWtHoZK3ueD862?utm_source=generator\" width=\"100%\" height=\"352\" frameBorder=\"0\" allowfullscreen=\"\" allow=\"autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture\" loading=\"lazy\"></iframe>"
      },
      {
        "mediaID": 6,
        "albumName": "Periphery 2",
        "releaseDate": "2012-07-03",
        "description": "Second studio album by American progressive metal band Periphery.",
        "runtime": "68:28",
        "numberOfTracks": 14,
        "coverImg": "https://m.media-amazon.com/images/I/61fbgcdw2OL._UF1000,1000_QL80_.jpg",
        "genre": ["Progressive Metal", "Djent"],
        "review": "A stunning sophomore effort that pushes the boundaries of progressive metal even further, showcasing Periphery`s evolution as songwriters and musicians with its seamless blend of technicality and melody.",
        "artist": "Periphery",
        "trackList": [
          "Muramasa",
          " Have a Blast",
          " Facepalm Mute",
          " Ji",
          " Scarlet",
          " Luck as a Constant",
          " Ragnarok",
          " The Gods Must Be Crazy!",
          " Make Total Destroy",
          " Erised",
          " Epoch",
          " Froggin` Bullfish",
          " Mile Zero",
          " Masamune"
        ],
        "spotifyLink": "<iframe style=\"border-radius:12px\" src=\"https://open.spotify.com/embed/album/6JfrPc1Vt7PHVd6B4dreQ7?utm_source=generator\" width=\"100%\" height=\"352\" frameBorder=\"0\" allowfullscreen=\"\" allow=\"autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture\" loading=\"lazy\"></iframe>"
      },
      {
        "mediaID": 7,
        "albumName": "This Place Will Become Your Tomb",
        "releaseDate": "2021-09-24",
        "description": "Second studio album by British progressive metal band Sleep Token.",
        "runtime": "43:36",
        "numberOfTracks": 12,
        "coverImg": "https://m.media-amazon.com/images/I/618PkCD118L._UF1000,1000_QL80_.jpg",
        "genre": ["Progressive Metal", "Post-Metal"],
        "review": "An ethereal and haunting album that seamlessly fuses elements of progressive metal, post-rock, and electronic music, creating a mesmerizing sonic journey that captivates the listener from start to finish.",
        "artist": "Sleep Token",
        "trackList": [
          "Atlantic",
          " Hypnosis",
          " Mine",
          " Like That",
          " The Love You Want",
          " Fall For Me",
          " Alkaline",
          " Distraction",
          " Descending",
          " Telomeres",
          " High Water",
          " Missing Limbs"
        ],
        "spotifyLink": "<iframe style=\"border-radius:12px\" src=\"https://open.spotify.com/embed/album/4SD2UxRO9OgeSCQK0PN7cC?utm_source=generator\" width=\"100%\" height=\"352\" frameBorder=\"0\" allowfullscreen=\"\" allow=\"autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture\" loading=\"lazy\"></iframe>"
      },
      {
        "mediaID": 8,
        "albumName": "ERRA",
        "releaseDate": "2021-03-19",
        "description": "Self-titled seventh studio album by American metalcore band ERRA.",
        "runtime": "47:14",
        "numberOfTracks": 10,
        "coverImg": "https://f4.bcbits.com/img/a0035632004_10.jpg",
        "genre": ["Metalcore", "Progressive Metal"],
        "review": "A masterclass in modern metalcore, ERRA`s self-titled album delivers a perfect blend of crushing heaviness, melodic hooks, and intricate guitar work, showcasing the bands maturity and growth as musicians.",
        "artist": "ERRA",
        "trackList": [
          "Snowblood",
          " Gungrave",
          " Divisionary",
          " House of Glass",
          " Shadow Autonomous",
          " Electric Twilight",
          " Scorpion Hymn",
          " Vanish Canvas",
          " Eidolon",
          " Remnant",
          " Memory Fiction"
        ],
        "spotifyLink": "<iframe style=\"border-radius:12px\" src=\"https://open.spotify.com/embed/album/3OuLJUIq1lBj8EUaoIQvWZ?utm_source=generator\" width=\"100%\" height=\"352\" frameBorder=\"0\" allowfullscreen=\"\" allow=\"autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture\" loading=\"lazy\"></iframe>"
      },
      {
        "mediaID": 9,
        "albumName": "Heavener",
        "releaseDate": "2022-02-04",
        "description": "Fourth studio album by American metalcore band Invent Animate.",
        "runtime": "48:21",
        "numberOfTracks": 11,
        "coverImg": "https://d24jnm9llkb1ub.cloudfront.net/icpn/197187359233/197187359233-cover-zoom.jpg",
        "genre": ["Metalcore", "Progressive Metal"],
        "review": "A sonic tour de force, \"Heavener\" combines atmospheric textures, punishing riffs, and emotive vocals to create a captivating listening experience that transcends genre boundaries and leaves a lasting impression.",
        "artist": "Invent Animate",
        "trackList": [
          "Absence Persistent",
          " Shade Astray",
          " Labyrinthine",
          " Without a Whisper",
          " False Meridian",
          " Reverie",
          " Immolation of Night",
          " Purity Weeps",
          " Void SUrfacing",
          " Emberglow",
          " Elysium"
        ],
        "spotifyLink": "<iframe style=\"border-radius:12px\" src=\"https://open.spotify.com/embed/album/0OUb9GCxls0erHrS98Htv1?utm_source=generator\" width=\"100%\" height=\"352\" frameBorder=\"0\" allowfullscreen=\"\" allow=\"autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture\" loading=\"lazy\"></iframe>"
      },
      {
        "mediaID": 10,
        "albumName": "Afterthoughts",
        "releaseDate": "2021-12-10",
        "description": "Second studio album by American metalcore band GreywInd.",
        "runtime": "41:22",
        "numberOfTracks": 10,
        "coverImg": "https://f4.bcbits.com/img/a4222978882_65",
        "genre": ["Metalcore", "Post-Hardcore"],
        "review": "An emotionally charged debut album that showcases Greywind`s talent for crafting anthemic rock songs with powerful vocals, heartfelt lyrics, and infectious energy, making it a standout in the alternative rock scene.",
        "artist": "Greywind",
        "trackList": [
          "Afterthoughts",
          " Forest Ablaze",
          " Circle",
          " Safe Haven",
          " The Lake",
          " Car Spin",
          " Stitch on My Wings",
          " Desolate",
          " In Autumn",
          " Wander"
        ],
        "spotifyLink": "<iframe style=\"border-radius:12px\" src=\"https://open.spotify.com/embed/album/4LgLhk8ciSBqFgZYzHr6UV?utm_source=generator\" width=\"100%\" height=\"352\" frameBorder=\"0\" allowfullscreen=\"\" allow=\"autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture\" loading=\"lazy\"></iframe>"
      },
      {
        "mediaID": 11,
        "albumName": "Souvenirs",
        "releaseDate": "2015-11-06",
        "description": "Second studio album by French metalcore band Novelists.",
        "runtime": "48:40",
        "numberOfTracks": 13,
        "coverImg": "https://merchbar.imgix.net/product/crop/1616/6127725/KYQIOD-1712965817-1500x1500-1712965810-4056813630961.jpg?q=40&auto=compress,format&ar=1:1&w=1400",
        "genre": ["Metalcore", "Progressive Metal"],
        "review": "A compelling blend of djent, metalcore, and progressive elements, \"Souvenirs\" is a thought-provoking album that explores themes of introspection, self-discovery, and resilience through its dynamic songwriting and impassioned performances.",
        "artist": "Novelists",
        "trackList": [
          "Inanimate",
          "Earth Grazer",
          "Gravity",
          "Antares",
          "Ouroboros",
          "Black Lights",
          "Voyager",
          "Muchos Touché",
          "Echoes",
          "5:12 AM",
          "The Lichtenberg Figure",
          "Souvenirs"
        ],
        "spotifyLink": "<iframe style=\"border-radius:12px\" src=\"https://open.spotify.com/embed/album/0QzSEPvsBdGazo5LZBgJf1?utm_source=generator\" width=\"100%\" height=\"352\" frameBorder=\"0\" allowfullscreen=\"\" allow=\"autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture\" loading=\"lazy\"></iframe>"
      }    
]
*/